### ISSUE TITLE
BerkShelf showing conflict error when installing package with 2.7.6 

### ISSUE THREAD

**Issue by drahamim** [chef-cookbooks/nginx#412] opened 2016-06-08 18:41 UTC
Berkshelf fails to install version of nginx cookbook newer then 1.8.0. 

Receive the following error. If I remove the nginx statement it works fine. 

Unable to satisfy constraints on package nginx due to solution constraint (nginx = 2.7.6). Solution constraints that may result in a constraint on nginx: [(nginx = 2.7.6)]
Demand that cannot be met: (nginx = 2.7.6)
Artifacts for which there are conflicting dependencies: nginx = 1.8.0 -> [(build-essential >= 0.0.0), (yum >= 0.0.0), (apt >= 0.0.0), (runit >= 0.0.0), (ohai >= 1.1.4)]Unable to find a solution for demands: apt (3.0.0), ark (1.0.1), ax-elasticsearch (0.1.0), build-essential (3.2.0), chef-client (4.3.3), chef-solo-search (0.5.1), chef-sugar (3.3.0), chef_handler (1.3.0), compat_resource (12.9.0), cron (1.7.6), elasticsearch (2.2.2), homebrew (2.1.0), iptables (2.2.0), java (1.39.0), logrotate (1.9.2), memcached (2.1.0), mysql (6.1.3), mysql-ct (0.1.1), nodejs (2.4.4), ntp (1.11.0), openssh (1.3.4), packagecloud (0.2.0), rbac (1.0.3), redisio (2.3.0), runit (1.7.6), seven_zip (2.0.0), sftp (1.0.10), sinopia (0.3.4), smf (2.2.8), ulimit (0.3.3), user (0.4.2), users (1.7.0), windows (1.39.2), yum (3.10.0), yum-epel (0.6.6), yum-mysql-community (0.2.0), nginx (= 2.7.6)

**Comment by hrak** [comment] 2016-06-09 09:41
Its caused by apt being pinned to '~> 2.2' in the 2.7.x branch and you are on apt 3.0.0.

I'm running into the same issue. Can apt be unpinned in nginx so we can determine which version of apt to run on a different level (like the environment f.e.)?

**Comment by bclow-invoca** [comment] 2016-06-09 23:01
ohai also being pinned to '~> 2.0' is causing issues on the 2.7.x branch.

**Comment by allaire** [comment] 2016-06-10 18:35
:+1:

**Comment by bclow-invoca** [comment] 2016-06-20 18:44
@allaire That solution does not work for all use cases.
Removing the hard pinning of the cookbooks in the metadata will allow Berks to manage the deps. It has been almost two weeks without a resolution, and the 3.0.0 version is not production ready.

**Comment by jdoss** [comment] 2016-06-23 15:24
Not sure if my reference to this issue from my PR notified this thread but I fixed this problem with my fork as it was blocking me from using Nginx with a new deployment. Removing the the hard pinning seemed to work without any issues.

**Comment by mjuarez** [comment] 2016-07-06 17:55
This is definitely has been a show stopper. Agree that 3.0.0 is not production ready, but 2.2.x is currently broken.

**Comment by jdoss** [comment] 2016-07-06 18:28
@mjuarez Yea I agree. It's a total blocker and I have the fix in a PR. ¯\_(ツ)_/¯

**Comment by stimko25** [comment] 2016-07-07 18:39
please push

**Comment by somedamnthing** [comment] 2016-07-29 18:03
Bumping, as build-essential is way past the 2.4.0 revision, which is the last revision the nginx cookbook will stand.

**Comment by jslusher** [comment] 2016-09-14 19:27
Hi there. Reading through this it seems as though I have to use an earlier version of the nginx cookbook to resolve the dependencies? I have a mess of a berks install I'm dealing with, as referenced by the issue I posted to berkshelf. I can't seem to get the 2.7.6 version to resolve anymore because of the ohai dependency mentioned above.

**Comment by jslusher** [comment] 2016-09-14 23:20
For anyone who runs into this issue, the fix was to change from this cookbook to the [chef_nginx](https://supermarket.chef.io/cookbooks/chef_nginx) cookbook, which is more directly supported by the chef community.

**Comment by eric-tucker** [comment] 2017-06-16 19:06
Is the 3.0 rewrite still being worked on?  The current state of this cookbook is not looking good.

**Comment by tas50** [comment] 2017-09-17 19:30
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435

**Closed by tas50** 2017-09-17 19:30 UTC
Labels: pre-3.0
