### ISSUE TITLE
v2.7.6 doesn't install passenger

### ISSUE THREAD

**Issue by krukgit** [chef-cookbooks/nginx#360] opened 2015-06-11 03:32 UTC
I have a cookbook I've been using for years that installs nginx from source, along with passenger module. It works perfectly fine with nginx cookbook 2.7.4 but fails when trying to use 2.7.6.

Setup: Ubuntu 14.04, Chef 11.12.8, rvm cookbook 0.10.1, nginx 1.9.1, passenger 5.0.9

Error:

```
...
checking for getaddrinfo() ... found
configuring additional modules
adding module in /usr/local/rvm/gems/ruby-2.2.2/gems/passenger-5.0.9/ext/nginx
./configure: error: no /usr/local/rvm/gems/ruby-2.2.2/gems/passenger-5.0.9/ext/nginx/config was found
```

Correct me if I'm wrong but from a brief look at the recipe, it would seem passenger module expects now to see `node['nginx']['passenger']['install_method']` which wasn't used  previously.

This is a breaking change in a minor version update. Shouldn't it at least have a sensible default value?

**Comment by rmoriz** [comment] 2015-06-16 09:28
Can you share your run_list/attributes for nginx cookbook?

**Comment by krukgit** [comment] 2015-06-24 10:21
```
# nginx                                                                                                                                                                                                                                                                       
normal['nginx']['version'] = '1.7.10'
normal['nginx']['dir'] = '/etc/nginx'
normal['nginx']['log_dir'] = '/var/log/nginx'
normal['nginx']['binary'] = "/opt/nginx-#{node['nginx']['version']}/sbin"
normal['nginx']['source']['sbin_path'] = "#{node['nginx']['binary']}/nginx"
normal['nginx']['init_style'] = 'init'
normal['nginx']['default_site_enabled'] = false
normal['nginx']['source']['version'] = node['nginx']['version']
normal['nginx']['source']['modules'] = ["nginx::http_stub_status_module",
                                        "nginx::http_ssl_module",
                                        "nginx::http_gzip_static_module",
                                        "nginx::passenger"]
normal['nginx']['source']['prefix'] = "/opt/nginx-#{node['nginx']['source']['version']}"
normal['nginx']['source']['default_configure_flags'] = ["--prefix=#{node['nginx']['source']['prefix']}",
                                                        "--conf-path=#{node['nginx']['dir']}/nginx.conf",
                                                        "--sbin-path=#{node['nginx']['source']['sbin_path']}"]
normal['nginx']['source']['url'] = "http://nginx.org/download/nginx-#{node['nginx']['source']['version']}.tar.gz"

# passenger                                                                                                                                                                                                                                                                   
normal['nginx']['passenger']['version'] = '5.0.1'
normal['nginx']['passenger']['ruby'] = "#{node['rvm']['root_path']}/wrappers/ruby-#{node['rvm']['default_ruby']}/ruby"
normal['nginx']['passenger']['gem_binary'] = "#{node['rvm']['root_path']}/wrappers/ruby-#{node['rvm']['default_ruby']}/gem"
normal['nginx']['passenger']['root'] = "#{node['rvm']['root_path']}/gems/ruby-#{node['rvm']['default_ruby']}/gems/passenger-#{node['nginx']['passenger']['version']}"
normal['nginx']['configure_flags'] = ["--add-module=#{node['rvm']['root_path']}/gems/ruby-#{node['rvm']['default_ruby']}/gems/passenger-#{node['nginx']['passenger']['version']}/ext/nginx"]
normal['nginx']['passenger']['packages']['debian'] = ["libcurl4-gnutls-dev"]
```

**Comment by rmoriz** [comment] 2015-06-24 12:00
rvm?

**Comment by krukgit** [comment] 2015-06-25 02:30
```
# rvm                                                                                                                                                                                                                                                                         
normal['rvm']['rubies'] = ['2.1.5']
normal['rvm']['default_ruby'] = node['rvm']['rubies'].first
normal['rvm']['user_default_ruby'] = node['rvm']['default_ruby']
normal['rvm']['gems'][node['rvm']['default_ruby']] = [{name: "bundler"}, {name: "rake"}]
normal['rvm']['gem_package']['rvm_string'] = node['rvm']['default_ruby']
normal['rvm']['gpg']['keyserver'] = "hkp://keys.gnupg.net"
normal['rvm']['gpg']['homedir'] = "/root"
normal['rvm']['install_rubies'] = true
```

My runlist wouldn't tell you much but the order in which I execute community cookbooks is:

```
apt
ntp
logrotate
chef_gem
rvm::system
rvm::gem_package
nginx::source
```

**Comment by whatcould** [comment] 2015-07-16 20:49
I had the same problem; setting ["install_method"] did not seem to help — there was no passenger in my ruby-2.2.2/gems directory.

I added `recipe[nginx::passenger]` before `recipe[nginx::source]` in my runlist, and that solved it.

I'm not sure what the issue is, since it seems that I've used 1.7.6 in another recipe a few months ago that successfully installed passenger.

**Comment by plainlystated** [comment] 2015-11-01 20:35
I believe the issue is here:

```
34 if node['nginx']['passenger']['install_method'] == 'package'                                                                                                                                                    
 35   package node['nginx']['package_name']                                                                                                                                                                         
 36   package 'passenger'                                                                                                                                                                                           
 37 elsif node['nginx']['passenger']['install_method'] == 'source'                                                                                                                                                  
 38                                                                                                                                                                                                                 
 39   gem_package 'passenger' do                                                                                                                                                                                    
 40     action     :install                                                                                                                                                                                         
 41     version    node['nginx']['passenger']['version']                                                                                                                                                            
 42     gem_binary node['nginx']['passenger']['gem_binary'] if node['nginx']['passenger']['gem_binary']                                                                                                             
 43   end                                                                                                                                                                                                           
 44                                                                                                                                                                                                                 
 45   node.run_state['nginx_configure_flags'] =                                                                                                                                                                     
 46     node.run_state['nginx_configure_flags'] | ["--add-module=#{node['nginx']['passenger']['root']}/ext/nginx"]                                                                                                  
 47                                                                                                                                                                                                                 
 48 end
```

the attribute node['nginx']['passenger']['install_method'] doesn't seem to exist. Is it supposed to be node['instlal_method'] ?

**Comment by tas50** [comment] 2017-09-17 19:33
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435

**Closed by tas50** 2017-09-17 19:33 UTC
Labels: pre-3.0
