### ISSUE TITLE
nginx 1.8.0 installed - ignoring default attributes?

### ISSUE THREAD

**Issue by dpresling** [chef-cookbooks/nginx#351] opened 2015-04-27 22:44 UTC
Running the latest tag with chef-client 12.2.1, nginx 1.8.0 is being installed which seems to be ignoring the default attributes which are set to 1.6.2. 

build   28-Apr-2015 10:21:44    [0mRecipe: nginx::package[0m[33m 
build   28-Apr-2015 10:21:44    [0m  \* apt_package[nginx] action install[2015-04-27T22:21:44+00:00] INFO: Processing apt_package[nginx] action install (nginx::package line 41)[33m  
build   28-Apr-2015 10:21:48    [0m[36m       [2015-04-27T22:21:48+00:00] INFO: apt_package[nginx] installed nginx at 1.8.0-1~precise
build   28-Apr-2015 10:21:48    [0m[36m  
build   28-Apr-2015 10:21:48    [0m    [32m- install version 1.8.0-1~precise of package nginx[0m[36m

**Comment by rmoriz** [comment] 2015-06-11 15:08
The version attribute is only used for source installs. Packages will be installed according to your apt/dpkg setup.

https://github.com/miketheman/nginx/blob/master/recipes/package.rb#L41-L45

**Comment by iennae** [comment] 2017-09-26 00:53
This is either a duplicate of #286, or a question that @rmoriz has helpfully already answered.

**Closed by iennae** 2017-09-26 00:53 UTC
Labels: pre-3.0
